import { DocCodeBlock } from "@/app/components/doc-code-block";
import { DocPageShell } from "@/app/components/doc-page-shell";
import { C, DocTable, GuideHeader, GuideSection, P } from "@/app/components/doc-guide";
import bundleSize from "@/app/data/bundle-size.json";
import { getDocNav } from "@/app/utils/doc-nav";

const kb = (bytes: number) => `${(bytes / 1000).toFixed(1)} KB`;

const STYLES_EXAMPLE = `import "@sinups/ai-kit/styles/base.css";
import "@sinups/ai-kit/styles/Wizard.css";`;

export default function BundleSizePage() {
  const { previousHref, nextHref } = getDocNav("/docs/bundle-size");

  return (
    <DocPageShell
      sections={[
        { id: "sizes", label: "Sizes" },
        { id: "how", label: "How it is measured" },
      ]}
    >
      <GuideHeader
        title="Bundle size"
        description="JavaScript and CSS each component adds to your app."
        previousHref={previousHref}
        nextHref={nextHref}
      >
        <P>
          Importing one component bundles that component and what it renders, not the whole kit.
          JavaScript is tree-shaken by your bundler; styles come per component when you import{" "}
          <C>styles/base.css</C> and <C>styles/&lt;Component&gt;.css</C> instead of{" "}
          <C>styles.css</C>.
        </P>
        <DocCodeBlock code={STYLES_EXAMPLE} language="tsx" />
      </GuideHeader>

      <GuideSection id="sizes" title="Sizes">
        <DocTable
          columns={["Import", "JS gzip", "CSS gzip", "Total gzip"]}
          rows={bundleSize.map((entry) => [
            <C key="name">{entry.name}</C>,
            kb(entry.jsGzip),
            entry.cssGzip ? kb(entry.cssGzip) : "none",
            kb(entry.totalGzip),
          ])}
        />
      </GuideSection>

      <GuideSection id="how" title="How it is measured">
        <P>
          Each row bundles a single import from the published build with esbuild, minified, with{" "}
          <C>react</C>, <C>react-dom</C> and <C>@mantine/*</C> left to your app. Icons and{" "}
          <C>markdown-to-jsx</C> are counted. CSS is <C>base.css</C> plus the component file, or{" "}
          <C>styles.css</C> for <C>import *</C>. The table is generated by <C>yarn size --json</C>,
          which also fails CI when an entry grows past its budget.
        </P>
      </GuideSection>
    </DocPageShell>
  );
}
