import { formatCount } from '../utils/format-count';
import type { DiffLabels } from './types';

export const DEFAULT_DIFF_LABELS: DiffLabels = {
  filesChanged: (files) => `${formatCount(files, 'file', 'files')} changed`,
  searchFiles: 'Filter files',
  statusFilter: 'Change status',
  allStatuses: 'All changes',
  statusAdded: 'Added',
  statusModified: 'Modified',
  statusDeleted: 'Deleted',
  statusRenamed: 'Renamed',
  viewList: 'List',
  viewTree: 'Tree',
  noFiles: 'No changes',
  noMatchingFiles: 'No matching files',
  unified: 'Unified',
  split: 'Split',
  copyPath: 'Copy path',
  pathCopied: 'Path copied',
  showUnchanged: (lines) => `Show ${formatCount(lines, 'unchanged line', 'unchanged lines')}`,
  binaryFile: 'Binary file',
  binaryFileDescription: 'The contents of binary files are not shown',
  deletedFile: 'File deleted',
  deletedFileDescription: (lines) => `${formatCount(lines, 'line', 'lines')} removed`,
  showContent: 'Show content',
  emptyFile: 'Empty file',
  renamedWithoutChanges: 'File renamed without content changes',
  viewed: 'Viewed',
  viewedCount: (viewed, total) => `${viewed} / ${total} viewed`,
  previousFile: 'Previous file',
  nextFile: 'Next file',
  accept: 'Accept',
  reject: 'Reject',
  acceptAll: 'Accept all',
  rejectAll: 'Reject all',
  accepted: 'Accepted',
  rejected: 'Rejected',
  back: 'All files',
  selectFile: 'Select a file to review',
  title: 'Review changes',
  retry: 'Retry',
  statusUntracked: 'Untracked',
  untrackedFile: 'New untracked file',
  untrackedFileDescription: (lines) => `${formatCount(lines, 'line', 'lines')}, not tracked yet`,
  fileTooLarge: 'File too large to display',
  fileTooLargeDescription: (size, limit) => `${size} is over the ${limit} limit`,
  showAnyway: 'Show anyway',
  changesSource: 'Changes',
  dismiss: 'Dismiss',
  closeSearch: 'Close search',
  lineAdded: 'Added line',
  lineRemoved: 'Removed line',
};

export function resolveDiffLabels(labels?: Partial<DiffLabels>): DiffLabels {
  return labels ? { ...DEFAULT_DIFF_LABELS, ...labels } : DEFAULT_DIFF_LABELS;
}
